import * as Actions from '../Action'
const initialState = {
    idCategory: '',
    category: [],
    banner: [
        {
            source: require('../../assets/image/banner1.jpg')
        },
        {
            source: require('../../assets/image/banner2.jpg')
        },
        {
            source: require('../../assets/image/banner3.jpg')
        },
        {
            source: require('../../assets/image/banner4.jpg')
        },
    ],
    promotion: [
        {   
            id: 'Cbdeli1_khuyenmai',
            title: 'Combo Deli 1',
            initPrice: '126000',
            discountPrice: '85000',
            image: require('../../assets/image/cbdeli1.png'),
            add: true,
            detailsCombo: [
                {   
                    name: 'Gà rán',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Burger Tôm',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Khoai tây chiên',
                    size: 'M',
                    quantity: 1,
                },
                {   
                    name: 'Pepsi',
                    size: 'M',
                    quantity: 1,
                },
            ],
            addMoreItems: [
                {   
                    name: 'Phô mai miếng',
                    size: '',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Trứng',
                    size: '',
                    quantity: 1,
                    price: '7000',
                    image: '',
                },
            ],
            addMoreSauces: [
                {   
                    name: 'Sốt đậu',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Phô Mai',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Buffalo',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt HS',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
            ]
        },
        {   
            id: 'Cbdeli2_khuyenmai',
            title: 'Combo Deli 2',
            initPrice: '201000',
            discountPrice: '135000',
            add: true,
            image: require('../../assets/image/cbdeli2.png'),
            detailsCombo: [
                {   
                    name: 'Gà rán',
                    size: '',
                    quantity: 2,
                },
                {   
                    name: 'Mì Ý',
                    size: 'size vừa',
                    quantity: 1,
                },
                {   
                    name: 'Khoai tây lắc',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Pepsi',
                    size: 'M',
                    quantity: 2,
                },
            ],
            addMoreItems: [],
            addMoreSauces: [
                {   
                    name: 'Sốt đậu',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Phô Mai',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Buffalo',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt HS',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
            ]
        },
        {   
            id: 'Cb79k_khuyenmai',
            title: 'Combo 79k',
            initPrice: '109000',
            discountPrice: '79000',
            image: require('../../assets/image/cb79k.png'),
            add: true,
            detailsCombo: [
                {   
                    name: 'Gà rán',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Mì Ý',
                    size: 'size vừa',
                    quantity: 1,
                },
                {   
                    name: 'Khoai tây chiên',
                    size: 'M',
                    quantity: 1,
                },
                {   
                    name: 'Pepsi',
                    size: 'M',
                    quantity: 1,
                },
            ],
            addMoreItems: [],
            addMoreSauces: [
                {   
                    name: 'Sốt đậu',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Phô Mai',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Buffalo',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt HS',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
            ]
        },
        {   
            id: 'Cb139k_khuyenmai',
            title: 'Combo 139k',
            initPrice: '174000',
            discountPrice: '139000',
            image: require('../../assets/image/cb139k.png'),
            add: true,
            detailsCombo: [
                {   
                    name: 'Gà rán',
                    size: '',
                    quantity: 2,
                },
                {   
                    name: 'Burger Bulgogi',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Khoai tây chiên',
                    size: 'M',
                    quantity: 1,
                },
                {   
                    name: 'Pepsi',
                    size: 'M',
                    quantity: 2,
                },
            ],
            addMoreItems: [
                {   
                    name: 'Phô mai miếng',
                    size: '',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Trứng',
                    size: '',
                    quantity: 1,
                    price: '7000',
                    image: '',
                },
            ],
            addMoreSauces: [
                {   
                    name: 'Sốt đậu',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Phô Mai',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Buffalo',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt HS',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
            ]
        },
        {   
            id: 'Cb189k_khuyenmai',
            title: 'Combo 189k',
            initPrice: '189000',
            discountPrice: '263000',
            image: require('../../assets/image/cb189k.png'),
            add: true,
            detailsCombo: [
                {   
                    name: 'Gà rán',
                    size: '',
                    quantity: 2,
                },
                {   
                    name: 'K-chicken',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Burger Tôm',
                    size: '',
                    quantity: 1,
                },
                {   
                    name: 'Khoai tây chiên',
                    size: 'M',
                    quantity: 1,
                },
                {   
                    name: 'Pepsi',
                    size: 'M',
                    quantity: 3,
                },
            ],
            addMoreItems: [
                {   
                    name: 'Phô mai miếng',
                    size: '',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Trứng',
                    size: '',
                    quantity: 1,
                    price: '7000',
                    image: '',
                },
            ],
            addMoreSauces: [
                {   
                    name: 'Sốt đậu',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Phô Mai',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt Buffalo',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
                {   
                    name: 'Sốt HS',
                    quantity: 1,
                    price: '5000',
                    image: '',
                },
            ]
        },
        {   
            id: 'Pizzateriyaki_khuyenmai',
            title: 'Pizza chicken Teriyaki',
            initPrice: '38000',
            discountPrice: '',
            image: require('../../assets/image/pizzaTeriyaki.png'),
            add: true,
            detailsCombo: [],
            addMoreItems: [
                {   
                    name: 'Gà Lắc',
                    size: '',
                    quantity: 1,
                    price: '43000',
                    image: '',
                    add: true,
                },
                {   
                    name: 'Khoai Tây Lắc',
                    size: '',
                    quantity: 1,
                    price: '39000',
                    image: '',
                    add: true,
                },
                {   
                    name: 'Phô Mai que',
                    size: '',
                    quantity: 1,
                    price: '35000',
                    image: '',
                    add: true,
                },
                {   
                    name: 'Cá Nugget',
                    size: '3 miếng',
                    quantity: 1,
                    price: '28000',
                    image: '',
                    add: true,
                },
                {   
                    name: 'Mực Rán',
                    size: '3 miếng',
                    quantity: 1,
                    price: '28000',
                    image: '',
                    add: true,
                },
                {   
                    name: 'Khoai Tây Chiên',
                    size: 'M',
                    quantity: 1,
                    price: '28000',
                    image: '',
                    add: true,
                },
            ],
            addMoreSauces: []
        },
    ],
    news: [
        {   
            id: '200',
            title: 'Tháng 10 - trọn vẹn yêu thương',
            image: require('../../assets/image/banner1.jpg'),
            highlight: `Chào đón "vũ trụ deal ngon" tháng 10 nha Fans ơi`,
            description: "Nghía xem có món 'My Favourite' của mấy bồ trong này hong nha",
            detail: 'Combo 79.000: Gà rán + Mì ý + Khoai tây chiên (M) + Pepsi (M) - Tiết kiệm 30.000 \n Combo 139.000: 2 Gà rán + Burger Bulgogi + Khoai tây chiên (M) + 2 Pepsi (M) - Tiết kiệm đến 35.000 \n Combo 189.000: 2 Gà rán + K-Chicken + Burger Tôm + Khoai tây chiên (M) + 3 Pepsi (M) - Tiết kiệm đến 74.000',
            caseApply: false,
            lor: 'Combo áp dụng từ ngày 01/10 đến 31/10/2023, Fans có thể dùng tại cửa hàng, mua mang về hoặc đặt hàng trên \b Ứng dụng LOTTERIA VN/website lotteria.vn hoặc gọi đến số 19006778 \n Lotteria giao hàng tận nơi MIỄN PHÍ cùng rất nhiều ưu đãi khác \n Cùng tới Lotteria gần nhất thưởng thức Combo tháng 10 cùng nhiều món ngon iu thích nha Fans ơi!!!',
            hashtag: ``,
        },
        {   id: '201',
            title: 'ria dele - combo mê li',
            image: require('../../assets/image/banner4.jpg'),
            highlight: ``,
            description: "Đặt ngay Combo cho ngày bùng nổ:",
            detail: 'Combo Deli 1: Gà rán + Burger Tôm + Khoai tây chiên (M) + Pepsi (M)\n Combo Deli 2: 2 Gà rán + 2 Mì ý (size vừa) + Khoai tây lắc + 2 Pepsi (M)',
            caseApply: true,
            lor: '- Chương trình áp dụng từ ngày 01/10 đến hết 31/10/2023\n - Chương trình áp dụng qua Hotline (19006778), App_Web Lotteria\n \b - Chương trình áp dụng ở một số cửa hàng. Bạn có thể xem danh sách cửa hàng áp dụng "ƯU ĐÃI" tại khu vực tìm kiếm cửa hàng bên dưới nhé',
            hashtag: ``,
        },
        {   id: '202',
            title: 'gà rán đậm chất hàn: K-chicken',
            image: require('../../assets/image/kchicken.jpg'),
            highlight: `Vị ngon chuẩn Hàn từ sốt Yangnyeom nguyên bản`,
            description: `Lấy cảm hứng từ món Gà rán sốt Yangnyeom tại Hàn Quốc, từng miếng gà thấm đẫm sốt với đầy đủ hương vị: chua - cay - mặn - ngọt, kết hợp cùng đậu phộng rang giòn thơm,\n Idol K-Chicken chính thức "debut" vào ngày 20/07/2023\n Giá chỉ 75.000đ/phần - Thử ngay`,
            detail: 'Thưởng thức Gà rán đậm chất Hàn, ưu đãi tràn ngập khi dùng K-Chicken Combo/set, tiết kiệm đến 33.000đ\n K-Chicken Set 1: phần K-Chicken + Khoai tây chiên (M) + Pepsi (M) giá 86.000đ\nK-Chicken Combo: 1 phần K-Chicken + Bulgogi Burger + Mì Ý + 2 Pepsi (M) giá chỉ 145.000đ',
            caseApply: false,
            lor: 'Tới liền Lotteria gần nhất thoaiiiii. Gét go!!!',
            hashtag: ``,
        },
        {   id: '203',
            title: 'ra mắt kem tornado mới',
            image: require('../../assets/image/tornado.jpg'),
            highlight: `Lộ diện 2 "idol" với visual cực cuốn - hứa hẹn khuấy đảo mùa hè cùng các RIA Fans:\n Tornado Dâu "ngon thần sầu" và Tornado Trà xanh "mát lạnh"`,
            description: `Thưởng thức ngay 2 siêu phẩm hot hit mùa hè này - "mlem" hơn nữa là ưu đãi`,
            detail: `"Mua 2 được 3" - Miễn phí 1 kem Tornado bất kỳ khi mua bộ đôi Kem Tornado Dâu và Trà xanh.\n Giá chỉ 20.000đ/ly - Triển nhan đi nè các bạn ơi!`,
            caseApply: false,
            lor: 'Ưu đãi áp dụng từ ngày 1/7 đến ngày 31/7/2023 tại các cửa hàng Lotteria toàn quốc.',
            hashtag: `#MyFAVOURITELOTTERIA #LotteriaVietnam #NewTornado`,
        },
        {   id: '204',
            title: 'lotteria đã có mặt tại game play together',
            image: require('../../assets/image/playtogether.jpg'),
            highlight: `Hế lô các thần dan của đảo Kaia, Lotteria vừa "khai trương" một cửa hàng mới tại khu trung tâm đó.\nCác bạn đã thử trải nghiệm chưa?`,
            description: `Cùng tham gia làm nhiệm vụ tìm gà rán để trang bị thêm mũ Lody cho tủ đồ của mình nha.\nBạn nào muốn "độ da" sang màu đỏ nâu khỏe khoắn thì thử liền món Gà rán H&S best seller tại cửa hàng Lotteria trên Play Together nhé!\nCùng chờ đón những sự kiện thú vị và vật phẩm hấp dẫn tại cửa hàng ảo Lotteria nha!\nHẹn gặp lại các bạn ở khu trung tâm đảo Kaia!!!`,
            detail: ``,
            caseApply: false,
            lor: '',
            hashtag: ``,
        },
        {   id: '205',
            title: 'chicken teriyaki pizza',
            image: require('../../assets/image/pizzaTeriyaki.png'),
            highlight: `Hế lô các thần dan của đảo Kaia, Lotteria vừa "khai trương" một cửa hàng mới tại khu trung tâm đó.\nCác bạn đã thử trải nghiệm chưa?`,
            description: `Cùng tham gia làm nhiệm vụ tìm gà rán để trang bị thêm mũ Lody cho tủ đồ của mình nha.\nBạn nào muốn "độ da" sang màu đỏ nâu khỏe khoắn thì thử liền món Gà rán H&S best seller tại cửa hàng Lotteria trên Play Together nhé!\nCùng chờ đón những sự kiện thú vị và vật phẩm hấp dẫn tại cửa hàng ảo Lotteria nha!\nHẹn gặp lại các bạn ở khu trung tâm đảo Kaia!!!`,
            detail: ``,
            caseApply: false,
            lor: '',
            hashtag: ``,
        },
    ],
    order: [
        {   
            id: '300',
            title: 'Bestseller',
            image: require('../../assets/image/order_bestseller.jpg'),
            listItems: [
                {   
                    id: 'Garanphan_bestseller',
                    title: 'Gà rán phần',
                    initPrice: 174000,
                    discountPrice: 139000,
                    image: require('../../assets/image/ChickenSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GasotHSphan_bestseller',
                    title: 'Gà sốt HS phần',
                    initPrice: 122000,
                    discountPrice: 93000,
                    image: require('../../assets/image/HSChickenSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgertom_bestseller',
                    title: 'Combo Burger Tôm',
                    initPrice: 90000,
                    discountPrice: 80000,
                    image: require('../../assets/image/ComboBurgerTom_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerbulgogi_bestseller',
                    title: 'Combo Burger Bulgogi',
                    initPrice: 90000,
                    discountPrice: 80000,
                    image: require('../../assets/image/ComboBurgerBulgogi_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LoySet_bestseller',
                    title: 'Loy Set',
                    initPrice: 174000,
                    discountPrice: 139000,
                    image: require('../../assets/image/LoySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LodySet_bestseller',
                    title: 'Lody Set',
                    initPrice: 165000,
                    discountPrice: 139000,
                    image: require('../../assets/image/LodySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LonySet_bestseller',
                    title: 'Lony Set',
                    initPrice: 233000,
                    discountPrice: 189000,
                    image: require('../../assets/image/LonySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LokingSet_bestseller',
                    title: 'Loking Set',
                    initPrice: 268000,
                    discountPrice: 209000,
                    image: require('../../assets/image/LokingSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'L4Set_bestseller',
                    title: 'L4 Set',
                    initPrice: 331000,
                    discountPrice: 269000,
                    image: require('../../assets/image/L4Set_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GaPie_bestseller',
                    title: 'Gà Pie',
                    initPrice: 44000,
                    discountPrice: 0,
                    image: require('../../assets/image/GaPie_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GaPie+Pepsi_bestseller',
                    title: 'Gà Pie + Pepsi (M)',
                    initPrice: 58000,
                    discountPrice: 49000,
                    image: require('../../assets/image/GaPie+Pepsi_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'PMQ_bestseller',
                    title: 'Phô Mai Que',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/PhoMaiQue_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '301',
            title: 'Khuyến mãi',
            image: require('../../assets/image/order_khuyenmai.jpg'),
            listItems: [
                {
                    id: 'Cbdeli1_khuyenmai',
                    title: 'Combo Deli 1',
                    initPrice: 126000,
                    discountPrice: 85000,
                    image: require('../../assets/image/ComboDeli1_khuyenmai.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbdeli2_khuyenmai',
                    title: 'Combo Deli 2',
                    initPrice: 201000,
                    discountPrice: 135000,
                    image: require('../../assets/image/ComboDeli2_khuyenmai.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cb79k_khuyenmai',
                    title: 'Combo 79k',
                    initPrice: 109000,
                    discountPrice: 79000,
                    image: require('../../assets/image/Combo79k_khuyenmai.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cb139k_khuyenmai',
                    title: 'Combo 139k',
                    initPrice: 174000,
                    discountPrice: 139000,
                    image: require('../../assets/image/Combo139k_khuyenmai.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cb189k_khuyenmai',
                    title: 'Combo 189k',
                    initPrice: 263000,
                    discountPrice: 189000,
                    image: require('../../assets/image/Combo189k_khuyenmai.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Pizzateriyaki_khuyenmai',
                    title: 'Pizza Chicken Teriyaki',
                    initPrice: 38000,
                    discountPrice: 0,
                    image: require('../../assets/image/pizzaTeriyaki.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '302',
            title: 'Gà rán',
            image: require('../../assets/image/order_garan.jpg'),
            listItems: [
                {
                    id: 'Kchicken_garan',
                    title: 'K-Chicken',
                    initPrice: 75000,
                    discountPrice: 0,
                    image: require('../../assets/image/K-chicken_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Garan1m_garan',
                    title: 'Gà rán (1 miếng)',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/Chicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Garan3m_garan',
                    title: 'Gà rán (3 miếng)',
                    initPrice: 105000,
                    discountPrice: 102000,
                    image: require('../../assets/image/Chicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Garan6m_garan',
                    title: 'Gà rán (6 miếng)',
                    initPrice: 210000,
                    discountPrice: 199000,
                    image: require('../../assets/image/Chicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GasotHS1m_garan',
                    title: 'Gà Sốt HS (1 miếng)',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/HSchicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GasotHS3m_garan',
                    title: 'Gà Sốt HS (3 miếng)',
                    initPrice: 120000,
                    discountPrice: 116000,
                    image: require('../../assets/image/HSchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GasotHS6m_garan',
                    title: 'Gà Sốt HS (6 miếng)',
                    initPrice: 240000,
                    discountPrice: 221000,
                    image: require('../../assets/image/HSchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotdau1m_garan',
                    title: 'Gà Sốt Đậu (1 miếng)',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/Beanchicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotdau3m_garan',
                    title: 'Gà Sốt Đậu (3 miếng)',
                    initPrice: 120000,
                    discountPrice: 116000,
                    image: require('../../assets/image/Beanchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotdau6m_garan',
                    title: 'Gà Sốt Đậu (6 miếng)',
                    initPrice: 240000,
                    discountPrice: 221000,
                    image: require('../../assets/image/Beanchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotpm1m_garan',
                    title: 'Gà Sốt Phô Mai (1 miếng)',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/Cheesechicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotpm3m_garan',
                    title: 'Gà Sốt Phô Mai (3 miếng)',
                    initPrice: 120000,
                    discountPrice: 116000,
                    image: require('../../assets/image/Cheesechicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotpm6m_garan',
                    title: 'Gà Sốt Phô Mai (6 miếng)',
                    initPrice: 240000,
                    discountPrice: 221000,
                    image: require('../../assets/image/Cheesechicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotbuffalo1m_garan',
                    title: 'Gà Sốt Buffalo (1 miếng)',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/Buffalochicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotbuffalo3m_garan',
                    title: 'Gà Sốt Buffalo (3 miếng)',
                    initPrice: 120000,
                    discountPrice: 116000,
                    image: require('../../assets/image/Buffalochicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotbuffalo6m_garan',
                    title: 'Gà Sốt Buffalo (6 miếng)',
                    initPrice: 240000,
                    discountPrice: 221000,
                    image: require('../../assets/image/Buffalochicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Ganuong1m_garan',
                    title: 'Gà nướng (1 miếng)',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/Grilledchicken1p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Ganuong3m_garan',
                    title: 'Gà nướng (3 miếng)',
                    initPrice: 120000,
                    discountPrice: 116000,
                    image: require('../../assets/image/Grilledchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Ganuong6m_garan',
                    title: 'Gà nướng (6 miếng)',
                    initPrice: 240000,
                    discountPrice: 221000,
                    image: require('../../assets/image/Grilledchicken3p_chicken.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '303',
            title: 'Gà rán phần',
            image: require('../../assets/image/order_garanphan.jpg'),
            listItems: [
                {
                    id: 'Kchickenset_garanphan',
                    title: 'K-Chicken Set',
                    initPrice: 117000,
                    discountPrice: 86000,
                    image: require('../../assets/image/K-chickenset_set.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Garanphan_bestseller',
                    title: 'Gà Rán Phần',
                    initPrice: 112000,
                    discountPrice: 83000,
                    image: require('../../assets/image/ChickenSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GasotHSphan_bestseller',
                    title: 'Gà Sốt HS Phần',
                    initPrice: 122000,
                    discountPrice: 93000,
                    image: require('../../assets/image/HSChickenSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotdauphan_garanphan',
                    title: 'Gà Sốt Đậu Phần',
                    initPrice: 122000,
                    discountPrice: 93000,
                    image: require('../../assets/image/Beanset_set.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotpmphan_garanphan',
                    title: 'Gà Sốt Phô Mai Phần',
                    initPrice: 122000,
                    discountPrice: 93000,
                    image: require('../../assets/image/Cheeseset_set.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gasotbuffalophan_garanphan',
                    title: 'Gà Sốt Buffalo Phần',
                    initPrice: 122000,
                    discountPrice: 93000,
                    image: require('../../assets/image/Buffaloset_set.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '304',
            title: 'Burger',
            image: require('../../assets/image/order_burger.jpg'),
            listItems: [
                {
                    id: 'Burgerlchicken_burger',
                    title: 'Burger LChicken',
                    initPrice: 50000,
                    discountPrice: 0,
                    image: require('../../assets/image/LChickenburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgerbo_burger',
                    title: 'Burger Bò',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/Beefburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burger22_burger',
                    title: 'Burger Double Double',
                    initPrice: 74000,
                    discountPrice: 0,
                    image: require('../../assets/image/BurgerDouDou_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgermozzarella_burger',
                    title: 'Burger Mozzarella',
                    initPrice: 86000,
                    discountPrice: 0,
                    image: require('../../assets/image/BurgerMozza_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgertom_burger',
                    title: 'Burger Tôm',
                    initPrice: 48000,
                    discountPrice: 0,
                    image: require('../../assets/image/Shrimpburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgerbulgogi_burger',
                    title: 'Burger Bulgogi',
                    initPrice: 48000,
                    discountPrice: 0,
                    image: require('../../assets/image/Bulgogiburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgerca_burger',
                    title: 'Burger Cá',
                    initPrice: 40000,
                    discountPrice: 0,
                    image: require('../../assets/image/Fishburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgerpm_burger',
                    title: 'Burger Phô Mai',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/Cheeseburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Burgerboteriyaki_burger',
                    title: 'Burger Bò Teriyaki',
                    initPrice: 43000,
                    discountPrice: 0,
                    image: require('../../assets/image/TeriyakiBeefburger_burger.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '305',
            title: 'Combo',
            image: require('../../assets/image/order_combo.jpg'),
            listItems: [
                {
                    id: 'Cbburgerlchicken_combo',
                    title: 'Combo Burger LChicken',
                    initPrice: 92000,
                    discountPrice: 82000,
                    image: require('../../assets/image/comboBurgerLChicken_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerbo_combo',
                    title: 'Combo Burger Bò',
                    initPrice: 77000,
                    discountPrice: 52000,
                    image: require('../../assets/image/comboBurgerBo_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburger22_combo',
                    title: 'Combo Burger Double Double',
                    initPrice: 116000,
                    discountPrice: 98000,
                    image: require('../../assets/image/comboBurger22_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgermozzarella_combo',
                    title: 'Combo Burger Mozzarella',
                    initPrice: 128000,
                    discountPrice: 107000,
                    image: require('../../assets/image/comboBurgerMozarella_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgertom_bestseller',
                    title: 'Combo Burger Tôm',
                    initPrice: 90000,
                    discountPrice: 80000,
                    image: require('../../assets/image/ComboBurgerTom_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerbulgogi_bestseller',
                    title: 'Combo Burger Bulgogi',
                    initPrice: 90000,
                    discountPrice: 80000,
                    image: require('../../assets/image/ComboBurgerBulgogi_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerca_combo',
                    title: 'Combo Burger Cá',
                    initPrice: 82000,
                    discountPrice: 68000,
                    image: require('../../assets/image/comboBurgerCa_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerpm_combo',
                    title: 'Combo Burger Phô Mai',
                    initPrice: 87000,
                    discountPrice: 72000,
                    image: require('../../assets/image/comboBurgerPM_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Cbburgerboteriyaki_combo',
                    title: 'Combo Burger Bò Teriyaki',
                    initPrice: 85000,
                    discountPrice: 70000,
                    image: require('../../assets/image/comboBurgerBoTeriyaki_combo.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '306',
            title: 'Cơm - Mì Ý',
            image: require('../../assets/image/order_commiy.jpg'),
            listItems: [
                {
                    id: 'Comgavien_commiy',
                    title: 'Cơm gà viên',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comgavien_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Combotrungpm_commiy',
                    title: 'Cơm Bò Trứng Phô Mai',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/combotrungpm_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Comterilchicken_commiy',
                    title: 'Cơm Teri LChicken',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comteriyaki_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Comgasotdau_commiy',
                    title: 'Cơm Gà Sốt Đậu',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comgasotdau_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'ComgasotHS_commiy',
                    title: 'Cơm Gà Sốt HS',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comgasotHS_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Comgasotpm_commiy',
                    title: 'Cơm Gà Sốt Phô Mai',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comgasotPM_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Comgasotbuffalo_commiy',
                    title: 'Cơm Gà Sốt Buffalo',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comgasotBuffalo_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Comthitbo_commiy',
                    title: 'Cơm Thịt Bò',
                    initPrice: 45000,
                    discountPrice: 0,
                    image: require('../../assets/image/comthitbo_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Miy_commiy',
                    title: 'Mì Ý',
                    initPrice: 32000,
                    discountPrice: 0,
                    image: require('../../assets/image/miy_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Miy(L)_commiy',
                    title: 'Mì Ý (L)',
                    initPrice: 42000,
                    discountPrice: 0,
                    image: require('../../assets/image/miy_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Miythitbo_commiy',
                    title: 'Mì Ý Thịt Bò',
                    initPrice: 42000,
                    discountPrice: 0,
                    image: require('../../assets/image/miythitbo_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Miythitbo(L)_commiy',
                    title: 'Mì Ý Thịt Bò (L)',
                    initPrice: 52000,
                    discountPrice: 0,
                    image: require('../../assets/image/miythitbo_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Supga_commiy',
                    title: 'Súp Gà',
                    initPrice: 12000,
                    discountPrice: 0,
                    image: require('../../assets/image/supga_commiy.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '307',
            title: 'Thức ăn nhẹ',
            image: require('../../assets/image/order_thucannhe.jpg'),
            listItems: [
                {
                    id: 'GaPie_bestseller',
                    title: 'Gà Pie',
                    initPrice: 44000,
                    discountPrice: 0,
                    image: require('../../assets/image/GaPie_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'GaPie+Pepsi_bestseller',
                    title: 'Gà Pie + Pepsi (M)',
                    initPrice: 49000,
                    discountPrice: 0,
                    image: require('../../assets/image/GaPie+Pepsi_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Khoaitaylac_thucannhe',
                    title: 'Khoai Tây Lắc',
                    initPrice: 39000,
                    discountPrice: 0,
                    image: require('../../assets/image/khoaitaylac_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Galac_thucannhe',
                    title: 'Gà Lắc',
                    initPrice: 43000,
                    discountPrice: 0,
                    image: require('../../assets/image/galac_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'PMQ_bestseller',
                    title: 'Phô Mai Que',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/PhoMaiQue_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Khoaitaychien_thucannhe',
                    title: 'Khoai Tây Chiên (M)',
                    initPrice: 28000,
                    discountPrice: 0,
                    image: require('../../assets/image/khoaitaychien_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Banhtao_thucannhe',
                    title: 'Bánh Táo',
                    initPrice: 20000,
                    discountPrice: 0,
                    image: require('../../assets/image/banhtao_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Mucran3m_thucannhe',
                    title: 'Mực Rán (3 miếng)',
                    initPrice: 28000,
                    discountPrice: 0,
                    image: require('../../assets/image/mucran3m_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Mucran5m_thucannhe',
                    title: 'Mực Rán (5 miếng)',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/mucran3m_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Canugget3m_thucannhe',
                    title: 'Cá Nugget (3 miếng)',
                    initPrice: 28000,
                    discountPrice: 0,
                    image: require('../../assets/image/canugget_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Canugget5m_thucannhe',
                    title: 'Cá Nugget (5 miếng)',
                    initPrice: 35000,
                    discountPrice: 0,
                    image: require('../../assets/image/canugget_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Canhgagion2m_thucannhe',
                    title: 'Cánh Gà Giòn (2 miếng)',
                    initPrice: 38000,
                    discountPrice: 0,
                    image: require('../../assets/image/canhgagion_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Canhgagion4m_thucannhe',
                    title: 'Cánh Gà Giòn (4 miếng)',
                    initPrice: 72000,
                    discountPrice: 0,
                    image: require('../../assets/image/canhgagion_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gaxienque1q_thucannhe',
                    title: 'Gà Xiên Que (1 que)',
                    initPrice: 31000,
                    discountPrice: 0,
                    image: require('../../assets/image/xienque_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Gaxienque2q_thucannhe',
                    title: 'Gà Xiên Que (2 que)',
                    initPrice: 50000,
                    discountPrice: 0,
                    image: require('../../assets/image/xienque_thucannhe.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '308',
            title: 'Phần ăn nhóm',
            image: require('../../assets/image/order_phanannhom.jpg'),
            listItems: [
                {
                    id: 'LoySet_bestseller',
                    title: 'Loy Set',
                    initPrice: 174000,
                    discountPrice: 139000,
                    image: require('../../assets/image/LoySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LodySet_bestseller',
                    title: 'Lody Set',
                    initPrice: 165000,
                    discountPrice: 139000,
                    image: require('../../assets/image/LodySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LonySet_bestseller',
                    title: 'Lony Set',
                    initPrice: 233000,
                    discountPrice: 189000,
                    image: require('../../assets/image/LonySet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'LokingSet_bestseller',
                    title: 'Loking Set',
                    initPrice: 268000,
                    discountPrice: 209000,
                    image: require('../../assets/image/LokingSet_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'L4Set_bestseller',
                    title: 'L4 Set',
                    initPrice: 331000,
                    discountPrice: 269000,
                    image: require('../../assets/image/L4Set_bestseller.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
        {   
            id: '309',
            title: 'Thức uống',
            image: require('../../assets/image/order_thucuong.jpg'),
            listItems: [
                {
                    id: 'Milo',
                    title: 'Milo',
                    initPrice: 20000,
                    discountPrice: 0,
                    image: require('../../assets/image/milo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Milkis',
                    title: 'Milkis',
                    initPrice: 22000,
                    discountPrice: 0,
                    image: require('../../assets/image/milkis.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Nuoccam',
                    title: 'Nước Cam',
                    initPrice: 27000,
                    discountPrice: 0,
                    image: require('../../assets/image/nuoccam.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Tralipton',
                    title: 'Trà Lipton',
                    initPrice: 18000,
                    discountPrice: 0,
                    image: require('../../assets/image/tralipton.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Pepsi0(L)',
                    title: 'Pepsi Zero (L)',
                    initPrice: 18000,
                    discountPrice: 0,
                    image: require('../../assets/image/pepsi0calo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Pepsi(L)',
                    title: 'Pepsi (L)',
                    initPrice: 18000,
                    discountPrice: 0,
                    image: require('../../assets/image/pepsi.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: '7up(L)',
                    title: '7 UP (L)',
                    initPrice: 18000,
                    discountPrice: 0,
                    image: require('../../assets/image/7up.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Mirinda(L)',
                    title: 'Mirinda (L)',
                    initPrice: 18000,
                    discountPrice: 0,
                    image: require('../../assets/image/mirinda.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Pepsi0',
                    title: 'Pepsi Zero (M)',
                    initPrice: 14000,
                    discountPrice: 0,
                    image: require('../../assets/image/pepsi0calo.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Pepsi',
                    title: 'Pepsi (M)',
                    initPrice: 14000,
                    discountPrice: 0,
                    image: require('../../assets/image/pepsi.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: '7up',
                    title: '7 UP (M)',
                    initPrice: 14000,
                    discountPrice: 0,
                    image: require('../../assets/image/7up.png'),
                    detailsCombo: [],
                    add: true,
                },
                {
                    id: 'Mirinda',
                    title: 'Mirinda (M)',
                    initPrice: 14000,
                    discountPrice: 0,
                    image: require('../../assets/image/mirinda.png'),
                    detailsCombo: [],
                    add: true,
                },
            ]
        },
    ]
}

export default (state = initialState, action) => {
    switch(action.type) {
        case Actions.CHANGE_CATEGORY_ORDERLIST_SUCCESS: {
            return {
                ...state,
                category: action.data.listItems,
                idCategory: action.data.id
            }
        }
        default: 
            return state
    }
}